# -*- coding: utf-8 -*-
"""MTR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DkNj5D1RopFS5pzOYYJaZZdCmUPOI5jQ
"""

# MTR Data
# https://data.gov.hk/en-data/dataset/mtr-data2-nexttrain-data

#https://rt.data.gov.hk/v1/transport/mtr/getSchedule.php?line=TML&sta=HUH
# Tuen Ma Line (TML)
# Hung Hom (HUH)

import urllib.request
import json
import time
import smtplib
from email.mime.text import MIMEText

def getData(url):
    response = urllib.request.urlopen(url)
    if(response.getcode()==200):
        data = response.read()
        jsonData = json.loads(data)
    else:
        print("Error occured", response.getcode())
    return jsonData

url = "https://rt.data.gov.hk/v1/transport/mtr/getSchedule.php?line=TCL&sta=SUN"
data = getData(url)
print(data)
print(data['sys_time'])

'''
coming_train = []

for i in data["data"]['TML-HUH']['UP']:
    print(type(i))
    for key, value in i.items():
      print(key, '->', value)
      if (key == 'dest'):
        coming_train.append(value)
      if (key == 'time'):
        coming_train.append(value)

print(coming_train)
'''

coming_train = []

for i in data["data"]['TCL-SUN']['DOWN']:
    print(type(i))
    for key, value in i.items():
      print(key, '->', value)
      if (key == 'dest'):
        coming_train.append(value)
      if (key == 'time'):
        coming_train.append(value)

print(coming_train)

subject = "Next coming trains"
sender = "sender@gmail.com"
recipients = ["recipients@gmail.com"]
password = "GOOGLE_KEY"
body = "Next Coming Trains \n\n" + str(coming_train)

def send_email(subject, body, sender, recipients, password):
    msg = MIMEText(body)
    msg['Subject'] = subject
    msg['From'] = sender
    msg['To'] = ', '.join(recipients)
    with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp_server:
       smtp_server.login(sender, password)
       smtp_server.sendmail(sender, recipients, msg.as_string())
    print("Message sent!")


send_email(subject, body, sender, recipients, password)